Api error interceptor could not parse some failed responses where there is no api error body
ioki-mobility/kmp-passenger-api pull request #21
Opened 2024-08-29 11:20 UTC by vhontar

2024-08-29 11:43 UTC, merged

2024-08-30 05:23 UTC, StefMa requested changes
Hey Vlad,
can you explain thst change to me please?!
I don't get it. Even though backend doesn't send us ErrorBody (which should be their fault? 🤔), why do we want to create an EMPTY ErrorBody and send them to the interceptors? Probably no interceptor is interested in it, right?

2024-08-30 05:23 UTC, StefMa commented on library/src/commonMain/kotlin/com/ioki/passenger/api/IokiService.kt
> +        if (code == com.ioki.passenger.api.result.HttpStatusCode.BAD_GATEWAY_502) {
We can import that

2024-09-06 12:46 UTC, vhontar commented
@StefMa 
Thank you for the question!

No, we still interested in empty body, because we need only status code from API. Unfortunately it crashes the application if we try to parse empty ApiErrorBody and it just stops execution. But we still need status code for some interceptors only.

Does it make sense? :)

2024-09-06 12:46 UTC, vhontar commented on library/src/commonMain/kotlin/com/ioki/passenger/api/IokiService.kt
> +        if (code == com.ioki.passenger.api.result.HttpStatusCode.BAD_GATEWAY_502) {
Yep, I’ll fix in the next PR 🙏🏻

2024-09-07 06:32 UTC, StefMa commented
Thanks for the explanation!
You say the app crashes, is that really the case? Because we had everything wrapped here in a try catch? Or was the problem that we don't reach the interceptors?

I also don't like thst we construct an empty ErrorBody. In higher level modules we might think that backend sends us an empty body.
Would it make sense to try to parse a nullable ErrorBody instead? And put a null ErrorBody to the interceptors? Would this make more sense? 🤔

2024-09-13 11:05 UTC, vlh-ioki commented
No, the doesn't crash because of the try/catch, but parser itself crashes, because there is empty body ApiBodyError sent by backend. 

I'd assume that `.body<ApiBodyError?>` won't work here.

![Screenshot 2024-09-13 at 13 01 14](https://github.com/user-attachments/assets/6f5c7c17-054c-4434-8091-260917d9ce48)

2024-09-13 11:20 UTC, vlh-ioki commented
We need unit tests here: https://github.com/ioki-mobility/kmp-passenger-api/issues/22